language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DB=mysql; MW=master
      php: 5.3
    - env: DB=mysql; MW=1.20.0
      php: 5.4
    - env: DB=sqlite; MW=1.22.0
      php: 5.6
    - env: DB=sqlite; MW=1.24.0
      php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-extension-manager.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always